framework:
  website: vertx.io/docs/vertx-web/java/
  version: 4.0

files:
  - target/server.jar

binaries:
  - target/server.jar
  - vertx.json

command: /usr/bin/java -XX:-RelaxAccessControlCheck -XX:+UseNUMA -XX:+UseParallelGC -XX:+AggressiveOpts -jar /opt/web/target/server.jar -instances 8 -options /opt/web/vertx.json
